name: CI/CD Pipeline - DevOps FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        run: docker build -t devops-fastapi .

      - name: Testar execução do container
        run: |
          docker run -d -p 8080:8080 --name test-fastapi devops-fastapi
          sleep 5
          curl --fail http://localhost:8080/health

      - name: Finalizar container
        run: docker rm -f test-fastapi
